chatbotAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
  # path for other apps
  path('users/', include('users.urls')),
  path('businessdata/', include('businessdata.urls')),
  path('chatbotsettings/', include('chatbotsettings.urls')),
  path('clientchat/', include('clientchat.urls')),
  path('agents/', include('agents.urls')),
  path('common/', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatbotsettings/urls.py
from django.urls import path
from . import views


app_name = 'chatbotsettings'

urlpatterns = [
  path('addchatbotsettings', views.addChatBotSettings, name='addchatbotsettings'),
  path('updatechatbotsettings/<int:pk>/', views.updateChatBotSettings, name='updatechatbotsettings'),
  path('deletechatbotsettings/<int:pk>/', views.deleteChatBotSettings, name='deletechatbotsettings'),
  path('chatbotsettingsmanagement', views.ChatBotSettingsManagement, name='chatbotsettingsmanagement'),

  # route for Ajax frontend to have access to chatbotsettings details for user webui dynamic change when user picks a chatbot
  path('chatbotdetails/<int:business_data_id>/', views.getChatbotDetails, name='getchatbotdetails'),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
  # business user
  path('registerbusinessuser', views.registerBusinessUser, name='registerbusinessuser'),
  path('loginbusinessuser', views.loginBusinessUser, name='loginbusinessuser'),
  path('logoutbusinessuser', views.logoutBusinessUser, name='logoutbusinessuser'),
  path('updatebusinessuser', views.updateBusinessUser, name='updatebusinessuser'),

  # client user
  path('registerclientuser', views.registerClientUser, name='registerclientuser'),
  path('loginclientuser', views.loginClientUser, name='loginclientuser'),
  path('logoutclientuser', views.logoutClientUser, name='logoutclientuser'),
  path('updateclientuser', views.updateClientUser, name='updateclientuser'),
  # path('clientusersettings', views.clientUserSettings, name='clientusersettings'),
]

chatbotsettings/models.py
import os
import hashlib
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.exceptions import ValidationError


class ChatBotSettings(models.Model):
  # maybe one to one to user here
  business_user = models.ForeignKey(
    User,
    null=True,
    on_delete=models.CASCADE
  )
  business_user_uuid = models.ForeignKey(
    "businessdata.BusinessUserData",
    to_field="uuid",
    null=True,
    on_delete=models.SET_NULL
  )
  name = models.CharField(max_length=40, unique=True)
  tone = models.CharField(max_length=40, blank=True)
  description = models.CharField(max_length=150, blank=True)
  expertise = models.CharField(max_length=100, blank=True)
  custom_greeting = models.CharField(max_length=100, blank=True)
  example_of_response = models.CharField(max_length=400, blank=True)
  origin = models.CharField(max_length=100, blank=True)
  age = models.IntegerField(default=18)
  dream = models.CharField(max_length=100, blank=True)
  # better than FileField as it validates if File is Image
  # file will be uploaded to MEDIA_ROOT/uploads
  avatar = models.ImageField(
    max_length=255,
    upload_to="uploads/chatbotsettings/",
    blank=True,
  )

  def __str__(self):
    return f"{self.name}: {self.description[:50]}...| From {self.business_user}-{self.business_user_uuid}"

  # this overrides the Django native delete() method
  # it deletes the avatar if any then the instance
  def delete(self, *args, **kwargs):
    # Delete the avatar file if it exists
    if self.avatar:
      avatar_path = os.path.join(settings.MEDIA_ROOT, self.avatar.name)
      if os.path.isfile(avatar_path):
        os.remove(avatar_path)
    # Call the superclass delete method to delete the model instance
    super().delete(*args, **kwargs)

  def clean_avatar(self):
    """Ensure the uploaded avatar filename is unique."""
    if self.avatar:
      filename = os.path.basename(self.avatar.name)

      # Check if another chatbot is using the same filename
      existing_avatar = ChatBotSettings.objects.filter(
        avatar__icontains=filename
        ).exclude(id=self.id).exists()

      if existing_avatar:
        raise ValidationError("This image filename is already being used by another ChatBot. Please upload a unique image.")

    return self.avatar

chatbotsettings/forms.py
from django.forms import ModelForm
from .models import ChatBotSettings
from django.contrib.auth.models import User



# ChatBotSetting record form
class ChatBotSettingsForm(ModelForm):
  class Meta:
    model = ChatBotSettings
    fields = [
      'name', 'tone', 'description', 'expertise', 'custom_greeting', 'example_of_response', 'origin', 'age', 'dream', 'avatar',
    ]
    labels = {
      'name': 'Bot name',
      'tone': 'Tone of voice',
      'description': 'Bot description',
      'expertise': 'Expert in ...',
      'custom_greeting': 'How should the Bot greets?',
      'example_of_response': 'Optional example of response',
      'origin': 'Where is the Bot from?',
      'age': 'How old is the Bot?',
      'dream': 'What is the Bot dreaming of?',
       'avatar': 'Bot logo or picture',
    }


# ChatBotSettings Update data records
class ChatBotSettingsUpdateForm(ModelForm):
  class Meta:
    model = ChatBotSettings
    fields = [
      'name', 'tone', 'description', 'expertise', 'custom_greeting', 'example_of_response', 'origin', 'age', 'dream', 'avatar',
    ]
    labels = {
      'name': 'Bot name',
      'tone': 'Tone of voice',
      'description': 'Bot description',
      'expertise': 'Expert in ...',
      'custom_greeting': 'How should the Bot greets?',
      'example_of_response': 'Optional example of response',
      'origin': 'Where is the Bot from?',
      'age': 'How old is the Bot?',
      'dream': 'What is the Bot dreaming of?',
       'avatar': 'Bot logo or picture',
    }

chatbotsettings/views.py
import os
import json
import logging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from .models import ChatBotSettings
from .forms import (
  ChatBotSettingsForm,
  ChatBotSettingsUpdateForm
)
from businessdata.models import BusinessUserData


# setup logger
chatbotsettings_app_logger = logging.getLogger('chatbotsettings')

def is_client_user(user):
  return user.groups.filter(name='client').exists()

def is_business_user(user):
  return user.groups.filter(name='business').exists()


@login_required(login_url='users:loginbusinessuser')
@user_passes_test(is_business_user, login_url='users:loginbusinessuser')
def ChatBotSettingsManagement(request):
  # we fetch all and then will fetch only what we need after having seen how it looks like in webui
  # adding `.values("<model field>", "<other model field>")`
  data = ChatBotSettings.objects.filter(business_user=request.user)
  context = {"data": data}
  return render(request, 'chatbotsettings/chatbotsettingsmanagement.html', context)

# add chatbot settings
@login_required(login_url='users:loginbusinessuser')
@user_passes_test(is_business_user, login_url='users:loginbusinessuser')
def addChatBotSettings(request):
  '''
    Handle adding chatbot settings.
  '''

  form = ChatBotSettingsForm()
  if request.method == 'POST':
    form = ChatBotSettingsForm(request.POST, request.FILES)
    if form.is_valid():
      chatbotsettings_data = form.save(commit=False)
      chatbotsettings_data.business_user = request.user


      # Check if the avatar already exists for this user
      avatar = request.FILES.get('avatar')
      if avatar:
        try:
          # Check if an existing ChatBotSettings has the same avatar for the same user
          existing_avatar = ChatBotSettings.objects.get(
            business_user=request.user,
            avatar__contains=avatar.name
          )

          chatbotsettings_app_logger.info("This image has already been used. Please upload a different one.")

          messages.error(
            request,
            "This image has already been used. Please upload a different one."
          )
          return redirect("chatbotsettings:addchatbotsettings")
        except ChatBotSettings.DoesNotExist:

          # No duplicate avatar exists, continue to save
          chatbotsettings_app_logger.info("Image double name doesn't exist")
          print("Image double name doesn't exist")

          pass

      chatbotsettings_data.save()

      chatbotsettings_app_logger.info("ChatBot settings added successfully!")

      messages.success(
        request,
        "ChatBot settings added successfully!"
      )
      return redirect("chatbotsettings:addchatbotsettings")
    else:

      chatbotsettings_app_logger.info("Form submission incorrect. Please enter correct information.")

      messages.error(
        request,
        "Form submission incorrect. Please enter correct information."
      )
  context = {'form': form}
  return render(request, 'chatbotsettings/addchatbotsettings.html', context)

# update chatbotsettings
@login_required(login_url='users:loginbusinessuser')
@user_passes_test(is_business_user, login_url='users:loginbusinessuser')
def updateChatBotSettings(request, pk):
  chatbot_settings_to_update = get_object_or_404(ChatBotSettings, pk=pk, business_user=request.user)
  form = ChatBotSettingsUpdateForm(instance=chatbot_settings_to_update)

  if request.method == 'POST':
    form = ChatBotSettingsUpdateForm(request.POST, request.FILES, instance=chatbot_settings_to_update)
    if form.is_valid():
      # Check if the avatar already exists for this user
      avatar = request.FILES.get('avatar')
      if avatar:
        try:
          # Check if an existing ChatBotSettings has the same avatar for the same user
          existing_avatar = ChatBotSettings.objects.get(
            business_user=request.user,
            avatar__contains=avatar.name
          )

          chatbotsettings_app_logger.info("This image has already been used. Please upload a different one.")

          messages.error(
            request,
            "This image has already been used. Please upload a different one."
          )
          return redirect("chatbotsettings:addchatbotsettings")
        except ChatBotSettings.DoesNotExist:
          # No duplicate avatar exists, continue to save
          chatbotsettings_app_logger.info("updateChatbotSettings function: No duplicate avatar exist, continue to save form")
          pass

      form.save()

      chatbotsettings_app_logger.info("ChatBot has been updated successfully.")
      messages.success(
        request,
        "ChatBot has been updated successfully."
      )
      return redirect("chatbotsettings:chatbotsettingsmanagement")
    else:
      chatbotsettings_app_logger.info("Form submission incorrect. Please enter correct information.")
      messages.error(
        request,
        "Form submission incorrect. Please enter correct information."
      )
  context = {'form': form}
  return render(request, "chatbotsettings/updatechatbotsettings.html", context)

# delete chatbot settings
@login_required(login_url="users:loginbusinessuser")
@user_passes_test(is_business_user, login_url='users:loginbusinessuser')
def deleteChatBotSettings(request, pk):
  chatbot_settings_to_delete = get_object_or_404(ChatBotSettings, id=pk, business_user=request.user)
  if request.method == "POST":
    chatbot_settings_to_delete.delete()

    chatbotsettings_app_logger.info("ChatBot settings has been successfully deleted.")
    messages.success(
      request,
      "ChatBot settings has been successfully deleted."
    )
    return redirect("chatbotsettings:chatbotsettingsmanagement")

# special route for frontend javascript to fetch chatbot settings
@login_required(login_url="users:loginclientuser")
@user_passes_test(is_client_user, login_url='users:loginclientuser')
def getChatbotDetails(request, business_data_id):
  try:
    # Fetch the BusinessUserData entry
    business_data = BusinessUserData.objects.get(pk=int(business_data_id))

    chatbotsettings_app_logger.info(f"Business Data: {business_data}")
    print("Business Data: ", business_data)

    # Check if a chat_bot is linked to the business_data
    if business_data.chat_bot:
      # Fetch the ChatBotSettings linked via the ForeignKey
      data = {
        "name": business_data.chat_bot.name,
        "age": business_data.chat_bot.age,
        "origin": business_data.chat_bot.origin,
        "dream": business_data.chat_bot.dream,
        "tone": business_data.chat_bot.tone,
        "description": business_data.chat_bot.description,
        "expertise": business_data.chat_bot.expertise,
        "avatar_url": business_data.chat_bot.avatar.url if business_data.chat_bot.avatar else "",
        "business_owner": business_data.user.username,
        "number": business_data.uuid,
      }
      chatbotsettings_app_logger.info(f"CHATBOT: {data}")
      print("CHATBOT: ", data)
      return JsonResponse(data)
    else:
      chatbotsettings_app_logger.info("error: No chatbot linked to the selected business data.")
      return JsonResponse({"error": "No chatbot linked to the selected business data."}, status=404)

  except BusinessUserData.DoesNotExist:
    chatbotsettings_app_logger.info("error: Business data not found.")
    return JsonResponse({"error": "Business data not found."}, status=404)

templates/chatbotsettings/addchatbotsettings.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Add ChatBot Settings{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="business_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">Add ChatBot Settings</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    {{ form.name|add_class_with_label:"form-control" }}
                    {{ form.tone|add_class_with_label:"form-control" }}
                    {{ form.description|add_class_with_label:"form-control" }}
                    {{ form.expertise|add_class_with_label:"form-control" }}
                    {{ form.custom_greeting|add_class_with_label:"form-control" }}
                    {{ form.example_of_response|add_class_with_label:"form-control" }}
                    {{ form.origin|add_class_with_label:"form-control" }}
                    {{ form.age|add_class_with_label:"form-control" }}
                    {{ form.dream|add_class_with_label:"form-control" }}
                    {{ form.avatar|add_class_with_label:"form-control" }}

                    <div class="d-flex justify-content-center mt-4">
                        <input class="btn action_btn" type="submit" value="Add ChatBot Settings">
                    </div>
                </form>
            </div>
            {% if form.errors %}
            <div class="alert alert-danger mt-4">
                {{ form.errors }}
            </div>
            {% endif %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    <a href="{% url 'chatbotsettings:chatbotsettingsmanagement' %}" class="btn btn-link">Back to Setting Management</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/chatbotsettings/chatbotsettingsmanagement.html
{% extends "base.html" %}

{% block title %}ChatBot Settings Management{% endblock %}

{% block content %}
<div class="mt-4"></div>
<div class="container table-container">
    <h1 class="text-center">Welcome, {{ user.username }}!</h1>
    <h2 class="text-center">Manage Your ChatBot Settings</h2>
    <p class="text-center">Note: Upload Business Data Before Creating Any ChatBot Settings.</p>
    <p class="text-center">Then come back here, to create your ChatBot Seeting.</p>

    <!-- Add New ChatBot Setting Button -->
    <div class="d-flex justify-content-end mb-3">
        <button class="btn btn-success btn-add" onclick="location.href='{% url 'chatbotsettings:addchatbotsettings' %}'">
            <i class="fas fa-plus"></i> Add New ChatBot Settings 
        </button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <td>name</td>
                <td>tone</td>
                <td>description</td>
                <td>expertise</td>
                <td>custom_greeting</td>
                <td>example_of_response</td>
                <td>origin</td>
                <td>age</td>
                <td>dream</td>
                <td>avatar</td>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.tone }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.expertise }}</td>
                    <td>{{ item.custom_greeting }}</td>
                    <td>{{ item.example_of_response }}</td>
                    <td>{{ item.origin }}</td>
                    <td>{{ item.age }}</td>
                    <td>{{ item.dream }}</td>
                    <td>
                      {% if item.avatar %}
                        <img src="{{ item.avatar.url }}" alt="Creditizens ChatBotAI Avatar">
                      {% else %}
                        <p>No Avatar Uploaded</p>
                      {% endif %}
                    </td>
                    <td class="action-buttons-cell">
                        <!-- Update Button -->
                        <a href="{% url 'chatbotsettings:updatechatbotsettings' item.id %}" class="btn btn-primary btn-action mx-1">
                            <i class="fas fa-edit"></i> Update Settings
                        </a>

                        <!-- Delete Button -->
                        <form method="POST" action="{% url 'chatbotsettings:deletechatbotsettings' item.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-action mx-1" onclick="return confirm('Are you sure you want to delete this item?');">
                                <i class="fas fa-trash-alt"></i> Delete
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/chatbotsettings/updatechatbotsettings.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Update ChatBot Settings{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="business_card">
        <div class="d-flex justify-content-center">
            <h3 id="form-title">Update ChatBot Settings</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form method="POST" enctype="multipart/form-data" action="">
                {% csrf_token %}
                    {{ form.name|add_class_with_label:"form-control" }}
                    {{ form.tone|add_class_with_label:"form-control" }}
                    {{ form.description|add_class_with_label:"form-control" }}
                    {{ form.expertise|add_class_with_label:"form-control" }}
                    {{ form.custom_greeting|add_class_with_label:"form-control" }}
                    {{ form.example_of_response|add_class_with_label:"form-control" }}
                    {{ form.origin|add_class_with_label:"form-control" }}
                    {{ form.age|add_class_with_label:"form-control" }}
                    {{ form.dream|add_class_with_label:"form-control" }}
                    {{ form.avatar|add_class_with_label:"form-control" }}
                    {% if form.question_answer_data.errors %}
                    <div class="error">
                        {{ form.question_answer_data.errors }}
                    </div>
                    {% endif %}
                <div class="d-flex justify-content-center mt-4">
                    <input class="btn action_btn" type="submit" value="Update ChatBot Settings">
                </div>
            </form>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger mt-4">
            {{ form.errors }}
        </div>
        {% endif %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
              <a href="{% url 'chatbotsettings:addchatbotsettings' %}" class="btn btn-link">Or Add New Chatbot Settings</a>
            </div>
            <div class="d-flex justify-content-center links">
                <a href="{% url 'chatbotsettings:chatbotsettingsmanagement' %}" class="btn btn-link">Back to ChatBot Settings Management</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}