businessdata/urls.py
from django.urls import path
from . import views


app_name = 'businessdata'

urlpatterns = [
  path('addbusinessdata', views.addBusinessData, name='addbusinessdata'),
  path('updatebusinessdata/<int:pk>/', views.updateBusinessData, name='updatebusinessdata'),
  path('deletebusinessdata/<int:pk>/', views.deleteBusinessData, name='deletebusinessdata'),
  path('businessdatamanagement', views.businessDataManagement, name='businessdatamanagement'),
]

chatbotAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
  # path for other apps
  path('users/', include('users.urls')),
  path('businessdata/', include('businessdata.urls')),
  path('chatbotsettings/', include('chatbotsettings.urls')),
  path('clientchat/', include('clientchat.urls')),
  path('agents/', include('agents.urls')),
  path('common/', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatbotsettings/urls.py
from django.urls import path
from . import views


app_name = 'chatbotsettings'

urlpatterns = [
  path('addchatbotsettings', views.addChatBotSettings, name='addchatbotsettings'),
  path('updatechatbotsettings/<int:pk>/', views.updateChatBotSettings, name='updatechatbotsettings'),
  path('deletechatbotsettings/<int:pk>/', views.deleteChatBotSettings, name='deletechatbotsettings'),
  path('chatbotsettingsmanagement', views.ChatBotSettingsManagement, name='chatbotsettingsmanagement'),

  # route for Ajax frontend to have access to chatbotsettings details for user webui dynamic change when user picks a chatbot
  path('chatbotdetails/<int:business_data_id>/', views.getChatbotDetails, name='getchatbotdetails'),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
  # business user
  path('registerbusinessuser', views.registerBusinessUser, name='registerbusinessuser'),
  path('loginbusinessuser', views.loginBusinessUser, name='loginbusinessuser'),
  path('logoutbusinessuser', views.logoutBusinessUser, name='logoutbusinessuser'),
  path('updatebusinessuser', views.updateBusinessUser, name='updatebusinessuser'),

  # client user
  path('registerclientuser', views.registerClientUser, name='registerclientuser'),
  path('loginclientuser', views.loginClientUser, name='loginclientuser'),
  path('logoutclientuser', views.logoutClientUser, name='logoutclientuser'),
  path('updateclientuser', views.updateClientUser, name='updateclientuser'),
  # path('clientusersettings', views.clientUserSettings, name='clientusersettings'),
]

templates/business/addbusinessdata.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Add Business Data{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="business_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">Add Business Data</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    {{ form.document_title|add_class_with_label:"form-control" }}
                    {{ form.question_answer_data|add_class_with_label:"form-control" }}
                    {{ form.chat_bot|add_class_with_label:"form-control" }}

                    <div class="d-flex justify-content-center mt-4">
                        <input class="btn action_btn" type="submit" value="Add Business Data">
                    </div>
                </form>
            </div>
            {% if form.errors %}
            <div class="alert alert-danger mt-4">
                {{ form.errors }}
            </div>
            {% endif %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    <a href="{% url 'businessdata:businessdatamanagement' %}" class="btn btn-link">Back to Data Management</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/business/businessdatamanagement.html
{% extends "base.html" %}

{% block title %}Business Data Management{% endblock %}

{% block content %}
<div class="mt-4"></div>
<div class="container table-container">
    <h1 class="text-center">Welcome, {{ user.username }}!</h1>
    <h2 class="text-center">Manage Your Business Data</h2>

    <!-- Add New Data Button -->
    <div class="d-flex justify-content-end mb-3">
        <button class="btn btn-success btn-add" onclick="location.href='{% url 'businessdata:addbusinessdata' %}'">
            <i class="fas fa-plus"></i> Add New Data
        </button>
    </div>

    <!-- Data Table -->
    <div class="table-wrapper">
    <table class="table table-bordered table-hover table-dark">
        <thead class="thead-light">
            <tr>
                <th>Document Title</th>
                <th>Default ChatBot</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
                <tr>
                    <td>{{ item.document_title }}</td>
                    <td>
                      {% if item.chat_bot__name %}
                        {{ item.chat_bot__name }}
                      {% else %}
                        No ChatBot Assigned
                      {% endif %}
                    </td>
                    <td class="action-buttons-cell">
                        <!-- Update Button -->
                        <a href="{% url 'businessdata:updatebusinessdata' item.id %}" class="btn btn-primary btn-action mx-1">
                            <i class="fas fa-edit"></i> Update Data
                        </a>

                        <!-- Delete Button -->
                        <form method="POST" action="{% url 'businessdata:deletebusinessdata' item.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-action mx-1" onclick="return confirm('Are you sure you want to delete this item?');">
                                <i class="fas fa-trash-alt"></i> Delete
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/business/updatebusinessdata.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Update Business Data{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="business_card">
        <div class="d-flex justify-content-center">
            <h3 id="form-title">Update Business Data</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.document_title|add_class_with_label:"form-control" }}
                {{ form.question_answer_data|add_class_with_label:"form-control" }}
                  
                {% if form.question_answer_data.errors %}
                  <div class="error">
                    {{ form.question_answer_data.errors }}
                  </div>
                {% endif %}
                  
                {{ form.chat_bot|add_class_with_label:"form-control" }}
                <div class="d-flex justify-content-center links">
                  <a href="{% url 'chatbotsettings:chatbotsettingsmanagement' %}">Need More Bot Settings?</a>
                </div>
                <div class="d-flex justify-content-center mt-4">
                    <input class="btn action_btn" type="submit" value="Update Business Data">
                </div>
            </form>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger mt-4">
            {{ form.errors }}
        </div>
        {% endif %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
              <a href="{% url 'businessdata:addbusinessdata' %}" class="btn btn-link">Or Add New Data</a>
            </div>
            <div class="d-flex justify-content-center links">
                <a href="{% url 'businessdata:businessdatamanagement' %}" class="btn btn-link">Back to Data Management</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}