businessdata/urls.py
from django.urls import path
from . import views


app_name = 'businessdata'

urlpatterns = [
  path('addbusinessdata', views.addBusinessData, name='addbusinessdata'),
  path('updatebusinessdata/<int:pk>/', views.updateBusinessData, name='updatebusinessdata'),
  path('deletebusinessdata/<int:pk>/', views.deleteBusinessData, name='deletebusinessdata'),
  path('businessdatamanagement', views.businessDataManagement, name='businessdatamanagement'),
]

chatbotAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('admin/', admin.site.urls),
  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
  # path for other apps
  path('users/', include('users.urls')),
  path('businessdata/', include('businessdata.urls')),
  path('chatbotsettings/', include('chatbotsettings.urls')),
  path('clientchat/', include('clientchat.urls')),
  path('agents/', include('agents.urls')),
  path('common/', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientchat/urls.py
from django.urls import path, include
from . import views


app_name = 'clientchat'

urlpatterns = [
  path('clientuserchat', views.clientUserChat, name='clientuserchat'),
]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
  # business user
  path('registerbusinessuser', views.registerBusinessUser, name='registerbusinessuser'),
  path('loginbusinessuser', views.loginBusinessUser, name='loginbusinessuser'),
  path('logoutbusinessuser', views.logoutBusinessUser, name='logoutbusinessuser'),
  path('updatebusinessuser', views.updateBusinessUser, name='updatebusinessuser'),

  # client user
  path('registerclientuser', views.registerClientUser, name='registerclientuser'),
  path('loginclientuser', views.loginClientUser, name='loginclientuser'),
  path('logoutclientuser', views.logoutClientUser, name='logoutclientuser'),
  path('updateclientuser', views.updateClientUser, name='updateclientuser'),
  # path('clientusersettings', views.clientUserSettings, name='clientusersettings'),
]

users/models.py
from django.db import models
# django built-in User model
from django.contrib.auth.models import User


class ClientUser(models.Model):
  user = models.OneToOneField(
    User,
    null=True,
    on_delete=models.CASCADE
  )
  nickname = models.CharField(max_length=40)
  picture = models.ImageField(
    max_length=255,
    upload_to="uploads/client_user/",
    blank=True
  )
  bio = models.CharField(max_length=255, blank=True)
  email = models.EmailField(unique=True, blank=True)

  def __str__(self):
    return f"{self.nickname}: {self.bio[:50]}..."

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import ClientUser


# create client user
class CreateBusinessUserForm(UserCreationForm):
  business_group = forms.CharField(
    initial='business',
    disabled=True,
    # Use HiddenInput if you don't want to show the group field
    widget=forms.HiddenInput()
  )
  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

# update business user
class UpdateBusinessUserForm(ModelForm):
    """
    Form to update user's information like username, email, and first/last name.
    """
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('A user with this email already exists.')
        return email


# create client user
class CreateClientUserForm(UserCreationForm):
  # we set the field
  email = forms.EmailField(required=True)
  nickname = forms.CharField(max_length=40)
  bio = forms.CharField(max_length=255, required=False)

  class Meta:
    # we will use the User model and put what needed in  ClientUser Form
    model = User
    fields = ['nickname', 'email', 'password1', 'password2']

  def save(self, commit=True):
    user = super().save(commit=False)
    user.username = self.cleaned_data['nickname']
    user.email = self.cleaned_data['email']

    if commit:

      user.save()

      client_user = ClientUser.objects.create(
        user=user,
        nickname=self.cleaned_data['nickname'],
        email=self.cleaned_data['email'],
        bio=self.cleaned_data.get('bio', ''),
      )

      client_user.save()

    return user

# update client user
class UpdateClientUserForm(forms.ModelForm):
    """
    Form to update user's information like username, email, nickname, bio, and picture.
    """

    # Additional fields for ClientUser
    nickname = forms.CharField(max_length=40)
    bio = forms.CharField(max_length=255, required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('A user with this email already exists.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

            # Get or create ClientUser related to User
            # get_or_create returns a tupple so it can written different ways depends on what we need
            # client_user, create = ...objects.get_or_create
            # client_user, _ = ....objects.get_or_create
            # Or just client_user = ...objects.get_or_create
            client_user, _ = ClientUser.objects.get_or_create(user=user)

            client_user.nickname = self.cleaned_data['nickname']
            client_user.bio = self.cleaned_data.get('bio', '')

            # Save the picture if provided
            picture = self.cleaned_data.get('picture')
            if picture:
                client_user.picture = picture

            client_user.save()

        return user

users/views.py
import os
import json
import logging
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.shortcuts import get_object_or_404
from django.contrib import messages
from .forms import (
  CreateBusinessUserForm,
  UpdateBusinessUserForm,
  # to create/update
  CreateClientUserForm,
  UpdateClientUserForm
)
from .models import ClientUser
import memcache
from django.http import HttpResponse


# setup logger
users_app_logger = logging.getLogger('users')

# Connecting to Memcached
mc = memcache.Client(['127.0.0.1:11211'], debug=1)

# setup function checks if user is client user
# and use in decorator for checks
def is_client_user(user):
  return user.groups.filter(name='client').exists()


#############################################################
#               BUSINESS USER                               #
#############################################################
# setup function that checks if user is business
# and use in decorator for group filtering views
def is_business_user(user):
  return user.groups.filter(name='business').exists()

# register user
def registerBusinessUser(request):
  '''
  This route will present by default empty registration form.
  When the user posts the form, it will use this same route to create the user.
  '''
  if request.method == 'POST':
    form = CreateBusinessUserForm(request.POST)

    # Check if the username already exists before form validation
    username = request.POST.get('username')
    if User.objects.filter(username=username).exists():
    
      users_app_logger.info(f"A user with the username '{username}' already exists.")
      messages.error(request, f"A user with the username '{username}' already exists.")
      form.add_error("username", f"A user with the username '{username}' already exists.")
      context = {'form': form}
      return render(request, 'users/registerbusinessuser.html', context)

    # Proceed with validating the form
    if form.is_valid():
      # Save the user and log them in
      user = form.save()

      # Add user to 'business' group
      business_group, created = Group.objects.get_or_create(name='business')
      user.groups.add(business_group)

      password = form.cleaned_data['password1']
      user = authenticate(username=username, password=password)

      if user:
        login(request, user)

        users_app_logger.info(f"Account has been created for {username}")
        messages.success(request, f"Account has been created for {username}")
        return redirect('users:loginbusinessuser')
      else:
        users_app_logger.info("Authentication failed after registration.")
        messages.error(request, "Authentication failed after registration.")
    else:
      users_app_logger.info("Invalid form submission. Please correct the errors.")
      messages.error(request, "Invalid form submission. Please correct the errors.")
  else:
    # Present an empty registration form by default
    form = CreateBusinessUserForm()

  context = {'form': form}
  return render(request, 'users/registerbusinessuser.html', context)


# update user
@login_required(login_url='users:loginuser')
@user_passes_test(is_business_user, login_url='users:loginbusinessuser')
def updateBusinessUser(request):
    """
    View to update the logged-in user's information.
    """
    user = get_object_or_404(User, pk=request.user.pk)
    form = UpdateBusinessUserForm(instance=user)

    if request.method == 'POST':
        form = UpdateBusinessUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()

            users_app_logger.info('Your profile has been updated successfully.')
            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('businessdata:businessdatamanagement')
        else:
            users_app_logger.info('Please correct the error below.')
            messages.error(request, 'Please correct the error below.')

    context = {'form': form}
    return render(request, 'users/updatebusinessuser.html', context)

# login user
def loginBusinessUser(request):
  # making sure user is redirected to index page when already logged in
  if request.user.is_authenticated:
    return redirect('businessdata:businessdatamanagement')

  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(request=request, username=username, password=password)
    if user is not None:
      if is_business_user(user):
        login(request, user)
        return redirect('businessdata:businessdatamanagement')
      else:
        users_app_logger.info('User is not a business user. Create a business account, then come back to login here.')
        messages.error(request, 'User is not a business user. Create a business account, then come back to login here.')
    else:
      users_app_logger.info('Username OR Password is incorrect')
      messages.info(request, 'Username OR Password is incorrect')

  context = {}
  return render(request, 'users/loginbusinessuser.html', context)

# logout user
def logoutBusinessUser(request):
  logout(request)
  users_app_logger.info('Business User logged out.')
  return redirect('users:loginbusinessuser')


#############################################################
#               CLIENT USER                                 #
#############################################################

# register user
def registerClientUser(request):

  if request.method == 'POST':
    form = CreateClientUserForm(request.POST)

    # Check if the username already exists before form validation
    username = request.POST.get('username')
    if User.objects.filter(username=username).exists():
    
      users_app_logger.info(f"A user with the username '{username}' already exists.")
      messages.error(request, f"A user with the username '{username}' already exists.")
      form.add_error("username", f"A user with the username '{username}' already exists.")
      context = {'form': form}
      return render(request, 'users/registerclientuser.html', context)

    # Proceed with validating the form
    if form.is_valid():
      # Save the user and log them in
      user = form.save()

      # Add user to 'business' group
      client_group, created = Group.objects.get_or_create(name='client')
      user.groups.add(client_group)

      username = form.cleaned_data.get('username')
      password = form.cleaned_data['password1']
      user = authenticate(username=user.username, password=password)

      if user:
        login(request, user)

        users_app_logger.info(f"Account has been created for {username}")
        messages.success(request, f"Account has been created for {username}")
        return redirect('users:loginclientuser')
      else:
        users_app_logger.info("Authentication failed after registration.")
        messages.error(request, "Authentication failed after registration.")
    else:
      users_app_logger.info("Invalid form submission. Please correct the errors.")
      messages.error(request, "Invalid form submission. Please correct the errors.")
  else:
    # Present an empty registration form by default
    form = CreateClientUserForm()

  context = {'form': form}
  return render(request, 'users/registerclientuser.html', context)


# update user will be used as user settings page to update
@login_required(login_url='users:loginclientuser')
@user_passes_test(is_client_user, login_url='users:loginclientuser')
def updateClientUser(request):
  """
  View to update the logged-in user's information.
  """
  user = get_object_or_404(User, pk=request.user.pk)
  form = UpdateClientUserForm(instance=user)

  if request.method == 'POST':
    # Include request.FILES to handle image uploads
    form = UpdateClientUserForm(request.POST, request.FILES, instance=user)
    if form.is_valid():
      form.save()

      users_app_logger.info('Your profile has been updated successfully.')
      messages.success(request, 'Your profile has been updated successfully.')
      return redirect('clientchat:clientuserchat')
    else:
      users_app_logger.info('Please correct the error below.')
      messages.error(request, 'Please correct the error below.')

  context = {'form': form}
  return render(request, 'users/updateclientuser.html', context)


# login user
def loginClientUser(request):
  # making sure user is redirected to index page when already logged in
  if request.user.is_authenticated:
    return redirect('clientchat:clientuserchat')

  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(request=request, username=username, password=password)
    if user is not None:
      if is_client_user(user):
        login(request, user)
        users_app_logger.info('Business User logged in.')
        return redirect('clientchat:clientuserchat')
      else:
        users_app_logger.info('User is not a client user. Create a client account, then come back to login here.')
        messages.error(request, 'User is not a client user. Create a client account, then come back to login here.')
    else:
      users_app_logger.info('Username OR Password is incorrect')
      messages.info(request, 'Username OR Password is incorrect')

  context = {}
  return render(request, 'users/loginclientuser.html', context)



# we make sure that when we logout the cache is emptied
def logoutClientUser(request):
  user = request.user
  cache_key = f"chat_{user.id}"
  # clear the cached messges on logout
  mc.delete(cache_key)
  logout(request)
  users_app_logger.info('Business User Logged Out.')
  return redirect('users:loginclientuser')

templates/users/BAK_registerbusinessuser.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Register Business User Account{% endblock %}

{% block content %}
<div class="container">
<div class="d-flex justify-content-center">
    <div class="user_card">
        <div class="d-flex justify-content-center">
            <h3 id="form-title">Register Business User Account</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
                {% csrf_token %}

                <!-- USERNAME -->
                <label for="id_unsername">Username</label>
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter your username" value="{{ form.username.value|default_if_none:'' }}">
                </div>
                {% if form.nickname.errors %}
                  <div class="text-danger">
                    {% for error in form.nickname.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- EMAIL -->
                <label for="id_email">Email</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                    </div>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter your email" value="{{ form.email.value|default_if_none:'' }}">
                </div>
                {% if form.email.errors %}
                  <div class="text-danger">
                    {% for error in form.email.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- PASSWORD -->
                <label for="id_password1">Password</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" id="id_password1" name="{{ form.password1.name }}" placeholder="Enter your password">
                </div>
                {% if form.password1.errors %}
                  <div class="text-danger">
                    {% for error in form.password1.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- PASSWORD2 -->
                <div class="input-group mb-2">
                <label for="id_password2">Confirm Password</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" id="id_password2" name="{{ form.password2.name }}" placeholder="Confirm your password">
                </div>
                {% if form.password2.errors %}
                  <div class="text-danger">
                    {% for error in form.password2.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <div class="d-flex justify-content-center mt-3">
                    <input class="btn register_btn" type="submit" value="Register Account">
                </div>
            </form>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger mt-3">
            {{ form.errors }}
        </div>
        {% endif %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                Already have an account? <a href="{% url 'users:loginbusinessuser' %}" class="ml-2">Login here</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/users/BAK_registerclientuser.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Register Client User Account{% endblock %}

{% block content %}
<div class="container">
<div class="d-flex justify-content-center">
    <div class="user_card">
        <div class="d-flex justify-content-center">
            <h3 id="form-title">Register Client User Account</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
              {% csrf_token %}

              <!-- NICKNAME -->
                <label for="id_nickname">Nickname</label>
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" id="id_nickname" name="nickname" placeholder="Enter your nickname" value="{{ form.nickname.value|default_if_none:'' }}">
                </div>
                {% if form.nickname.errors %}
                  <div class="text-danger">
                    {% for error in form.nickname.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- EMAIL -->
                <label for="id_email">Email</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                    </div>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter your email" value="{{ form.email.value|default_if_none:'' }}">
                </div>
                {% if form.email.errors %}
                  <div class="text-danger">
                    {% for error in form.email.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- BIO -->
                <label for="id_bio">Bio</label>
                <div class="input-group mb-2">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user-edit"></i></span>
                  </div>
                    <input type="text" class="form-control" id="id_bio" name="bio" placeholder="Enter your bio" value="{{ form.bio.value|default_if_none:'' }}">
                  </div>
                </div>
                {% if form.bio.errors %}
                  <div class="text-danger">
                    {% for error in form.bio.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- PASSWORD -->
                <label for="id_password1">Password</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" id="id_password1" name="{{ form.password1.name }}" placeholder="Enter your password">
                </div>
                {% if form.password1.errors %}
                  <div class="text-danger">
                    {% for error in form.password1.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <!-- PASSWORD2 -->
                <div class="input-group mb-2">
                <label for="id_password2">Confirm Password</label>
                <div class="input-group mb-2">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" class="form-control" id="id_password2" name="{{ form.password2.name }}" placeholder="Confirm your password">
                </div>
                {% if form.password2.errors %}
                  <div class="text-danger">
                    {% for error in form.password2.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}

                <div class="d-flex justify-content-center mt-3">
                    <input class="btn register_btn" type="submit" value="Register Account">
                </div>
            </form>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger mt-3">
            {{ form.errors }}
        </div>
        {% endif %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                Already have an account? <a href="{% url 'users:loginclientuser' %}" class="ml-2">Login here</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/users/registerclientuser.html
{% extends "base.html" %}
{% load form_tags %}

{% block title %}Register Client User Account{% endblock %}

{% block content %}
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="user_card">
      <div class="d-flex justify-content-center">
        <h3 id="form-title">Register Client User Account</h3>
      </div>
      <div class="d-flex justify-content-center form_container">
        <form method="POST" action="">
          {% csrf_token %}

          <!-- NICKNAME -->
          <label for="id_nickname">Nickname</label>
          <div class="input-group mb-3">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" id="id_nickname" name="nickname" placeholder="Enter your nickname" value="{{ form.nickname.value|default_if_none:'' }}">
          </div>
          {% if form.nickname.errors %}
          <div class="text-danger">
            {% for error in form.nickname.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          <!-- EMAIL -->
          <label for="id_email">Email</label>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter your email" value="{{ form.email.value|default_if_none:'' }}">
          </div>
          {% if form.email.errors %}
          <div class="text-danger">
            {% for error in form.email.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          <!-- BIO -->
          <label for="id_bio">Bio</label>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user-edit"></i></span>
            </div>
            <input type="text" class="form-control" id="id_bio" name="bio" placeholder="Enter your bio" value="{{ form.bio.value|default_if_none:'' }}">
          </div>
          {% if form.bio.errors %}
          <div class="text-danger">
            {% for error in form.bio.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          <!-- PASSWORD1 -->
          <label for="id_password1">Password</label>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" id="id_password1" name="{{ form.password1.name }}" placeholder="Enter your password">
          </div>
          {% if form.password1.errors %}
          <div class="text-danger">
            {% for error in form.password1.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          <!-- PASSWORD2 -->
          <label for="id_password2">Confirm Password</label>
          <div class="input-group mb-2">
            <div class="input-group-append">
              <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" class="form-control" id="id_password2" name="{{ form.password2.name }}" placeholder="Confirm your password">
          </div>
          {% if form.password2.errors %}
          <div class="text-danger">
            {% for error in form.password2.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          <div class="d-flex justify-content-center mt-3">
            <input class="btn register_btn" type="submit" value="Register Account">
          </div>
        </form>
      </div>
      {% if form.errors %}
      <div class="alert alert-danger mt-3">
        {{ form.errors }}
      </div>
      {% endif %}
      <div class="mt-4">
        <div class="d-flex justify-content-center links">
          Already have an account? <a href="{% url 'users:loginclientuser' %}" class="ml-2">Login here</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}